# Generated by Django 5.2.17 on 2026-10-05 06:01

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('required_skills', models.JSONField(default=list)),
                ('min_experience_months', models.PositiveIntegerField(default=0)),
                ('max_notice_period_days', models.PositiveIntegerField(default=90)),
                ('max_salary', models.DecimalField(decimal_places=2, default=800000, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_file', models.FileField(upload_to='batches/source/')),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='QUEUED', max_length=15)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('processed_rows', models.PositiveIntegerField(default=0)),
                ('accepted_count', models.PositiveIntegerField(default=0)),
                ('rejected_count', models.PositiveIntegerField(default=0)),
                ('accepted_file', models.FileField(blank=True, upload_to='batches/results/')),
                ('rejected_file', models.FileField(blank=True, upload_to='batches/results/')),
                ('error', models.TextField(blank=True)),
                ('task_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('college', models.CharField(blank=True, max_length=200)),
                ('skills', models.TextField()),
                ('experience_months', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(600)])),
                ('notice_period_days', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(365)])),
                ('expected_salary', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('resume_text', models.TextField(blank=True)),
                ('portfolio_url', models.URLField(blank=True)),
                ('historical_selection_status', models.CharField(blank=True, max_length=15)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('SHORTLISTED', 'Shortlisted'), ('INTERVIEW', 'Interview'), ('SELECTED', 'Selected'), ('WAITLISTED', 'Waitlisted'), ('REJECTED', 'Rejected')], default='NEW', max_length=15)),
                ('resume_file', models.FileField(blank=True, upload_to='resumes/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'txt', 'docx'])])),
                ('image', models.ImageField(blank=True, upload_to='photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidates', to='recruitment.applicationbatch')),
                ('applied_role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='candidates', to='recruitment.jobrole')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InterviewSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('location', models.CharField(default='Office', max_length=200)),
                ('candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interview_slots', to='recruitment.candidate')),
                ('interviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interview_slots', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recruitment.jobrole')),
            ],
            options={
                'ordering': ['starts_at'],
            },
        ),
        migrations.CreateModel(
            name='InterviewFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comments', models.TextField()),
                ('recommendation', models.CharField(choices=[('SELECTED', 'Selected'), ('WAITLISTED', 'Waitlisted'), ('REJECTED', 'Rejected')], max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('slot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='recruitment.interviewslot')),
            ],
        ),
        migrations.CreateModel(
            name='ScreeningResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_passed', models.BooleanField(default=False)),
                ('rule_reasons', models.JSONField(default=list)),
                ('ml_probability', models.FloatField(blank=True, null=True)),
                ('keyword_score', models.FloatField(default=0)),
                ('matched_skills', models.JSONField(default=list)),
                ('pos_tags', models.JSONField(default=list)),
                ('model_version', models.CharField(blank=True, max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='screening', to='recruitment.candidate')),
            ],
        ),
        migrations.AddConstraint(
            model_name='interviewslot',
            constraint=models.CheckConstraint(condition=models.Q(('ends_at__gt', models.F('starts_at'))), name='slot_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='interviewslot',
            constraint=models.UniqueConstraint(fields=('interviewer', 'starts_at'), name='unique_interviewer_start'),
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['applied_role', 'status'], name='recruitment_applied_eda8c2_idx'),
        ),
        migrations.AddConstraint(
            model_name='candidate',
            constraint=models.CheckConstraint(condition=models.Q(('expected_salary__gte', 0)), name='salary_nonnegative'),
        ),
    ]
