# Generated by Django 5.2.17 on 2026-10-05 06:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobrole',
            name='code',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z][A-Z0-9_-]{1,19}$', 'Use 2–20 uppercase letters, digits, hyphens, or underscores; start with a letter.')]),
        ),
    ]
